// Sender ESP32 - UART2
HardwareSerial MySerial(2); // UART2

String messages[100] = {
  "FLASH_ESP32","BLINK_LED_ON","BLINK_LED_OFF","POWER_ON_ESP","POWER_OFF_ESP",
  "CHECK_UART","UPLOAD_FIRMWARE","ERASE_FLASH","READ_MAC_ADDRESS","RESET_DEVICE",
  "ENABLE_WIFI","DISABLE_WIFI","SCAN_WIFI","CONNECT_WIFI","DISCONNECT_WIFI",
  "ENABLE_BLUETOOTH","DISABLE_BLUETOOTH","START_BLE","STOP_BLE","CHECK_SIGNAL",
  "READ_TEMPERATURE","READ_HUMIDITY","READ_PRESSURE","START_ADC","STOP_ADC",
  "START_DAC","STOP_DAC","ENABLE_PWM","DISABLE_PWM","SET_PWM_DUTY",
  "START_TIMER","STOP_TIMER","RESET_TIMER","ENABLE_INTERRUPT","DISABLE_INTERRUPT",
  "CHECK_GPIO_STATUS","SET_GPIO_HIGH","SET_GPIO_LOW","READ_GPIO","CONFIGURE_PIN",
  "ENABLE_SPI","DISABLE_SPI","ENABLE_I2C","DISABLE_I2C","ENABLE_UART2","DISABLE_UART2",
  "CHECK_MEMORY","READ_FLASH","WRITE_FLASH","CHECK_BOOTLOADER",
  "ENTER_SLEEP_MODE","EXIT_SLEEP_MODE","ENABLE_DEEP_SLEEP","WAKE_FROM_SLEEP","CHECK_BATTERY",
  "ENABLE_RTC","DISABLE_RTC","SYNC_TIME","GET_SYSTEM_TIME","SET_SYSTEM_TIME",
  "ENABLE_WDT","DISABLE_WDT","RESET_WDT","CHECK_WDT_STATUS","ENABLE_LOGGING",
  "DISABLE_LOGGING","READ_LOGS","CLEAR_LOGS","CHECK_FIRMWARE_VERSION","UPDATE_FIRMWARE",
  "ENABLE_SECURITY","DISABLE_SECURITY","CHECK_ENCRYPTION","ENABLE_TLS","DISABLE_TLS",
  "START_HTTP_SERVER","STOP_HTTP_SERVER","START_MQTT","STOP_MQTT","CHECK_NETWORK_STATUS",
  "ENABLE_SENSOR_MODE","DISABLE_SENSOR_MODE","CALIBRATE_SENSOR","RESET_SENSOR","START_STREAM",
  "STOP_STREAM","CHECK_STORAGE","FORMAT_STORAGE","ENABLE_DEBUG","DISABLE_DEBUG",
  "SYSTEM_STATUS","DEVICE_INFO","HARDWARE_CHECK","SOFTWARE_CHECK","FINALIZE_PROCESS",
  "REBOOT_DEVICE","SAFE_MODE","NORMAL_MODE","START_SEQUENCE","END_SEQUENCE"
};

void setup() {
  Serial.begin(115200);                    // PC monitor
  MySerial.begin(115200, SERIAL_8N1, 16, 17); // RX2=16, TX2=17 to receiver
  delay(2000);
  Serial.println("SENDER READY");
}

void loop() {
  for (int i = 0; i < 100; i++) {
    MySerial.println(messages[i]);  // Send to receiver
    Serial.println(messages[i]);    // Print on PC monitor
    delay(50);                      // Small delay
  }

  while(true){ delay(1000); }        // Stop after sending
}
